### ISSUE TITLE
galaxy gemini install fails

### ISSUE THREAD

**Issue by deanasnyder** [arq5x/gemini#378]
After two tries (using two differently configured galaxy installs) the installation of gemini failed with the same results both times - 3 out of the 8 tools exhibit the status "installed, missing tool dependencies".

As a preliminary, pre-production test I am just doing the latest, default galaxy install on a single box, then the default gemini install using the galaxy gui.

The galaxy gui does lists 15 tools in the "gemini" sub-group I created, but I have not actually tested any of them due to the status warnings mentioned above.

Any ideas about what is happening here?

**Comment by deanasnyder** [comment]
Here's the error message from the gemini package install:

2015-02-13 13:59:14 (4.85 MB/s) - “Miniconda-3.5.5-Linux-x86_64.sh” saved [20736312/20736312]
Python 2.7.7 :: Continuum Analytics, Inc.
Traceback (most recent call last):
  File "gemini_install.py", line 325, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 61, in main
    gemini = install_gemini(anaconda, remotes, args.datadir, args.tooldir, args.sudo)
  File "gemini_install.py", line 107, in install_gemini
    _add_missing_inits(python_bin)
  File "gemini_install.py", line 164, in _add_missing_inits
    library_loc = subprocess.check_output("%s -c 'import pygraph.classes.graph; "
AttributeError: 'module' object has no attribute 'check_output'

**Comment by deanasnyder** [comment]
The python version on my redhat 6.5 install is 2.6.6.

**Comment by chapmanb** [comment]
Sorry about the install problem -- the installer script was not compatible with python 2.6 (which doesn't have the `check_output` function in `subprocess`). I pushed a fix that will let this work with 2.6 now, so hopefully it will be good to go if you re-try the run. I'm not 100% sure how the Galaxy installer works, so you may have to remove local cached version of `gemini_install.py` if it doesn't always pull the latest version from GitHub.

Thanks much for the report and hope this fixes it for you.

**Comment by deanasnyder** [comment]
I believe that fixed the install issue, but not sure because:

1) I can't figure out how to run the Gemini test suite under a Galaxy install.
2) I can't figure out how to load a Gemini database to run some Gemini tool tests via Galaxy.
